### ISSUE TITLE
トーン調整UIの透明度

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2-Editor#1]
https://github.com/litagin02/Style-Bert-VITS2/issues/78#issue-2155713845
写真の移動がめんどいのでご参照ください。

**Comment by litagin02** [comment]
![image](https://github.com/litagin02/Style-Bert-VITS2-Editor/assets/139731664/8eec2479-5890-47af-a97c-005620f4d753)

Editor ver 0.2.4にて修正しました（もともとこういうスクロールバー出る挙動にしていたのがどこかのタイミングでバグっていたのに気づかなかったので、そう修正です。）
