### ISSUE TITLE
モデル更新をメニューから...

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2-Editor#4]
APIにモデル更新がないようだけど、マージした時とかに使用するので...

**Comment by litagin02** [comment]
https://github.com/litagin02/Style-Bert-VITS2-Editor/commit/29e5273f8ff5879a7ae880d772ca59856ad9c0ac
にて追加し、v0.3以降で追加されました。要望ありがとうございました。
