### ISSUE TITLE
エディターの「話速」に関する表示

### ISSUE THREAD

**Issue by OzoneAsai** [litagin02/Style-Bert-VITS2-Editor#6]
エディターの「話速」に関する表示(本来はlengthになるため、数字が大きいほど遅い。これは「話速」のイメージに反する[用出典]

**Comment by litagin02** [comment]
いいえ、エディター側の話速はlengthパラメータとは違っています（lengthパラメータに渡すときに逆数を取って変換しています）。なので話速は大きいほど速くなります。
